[colors.bright]
black   = "#5e5c64"
blue    = "#2a7bde"
cyan    = "#33c7de"
green   = "#33d17a"
magenta = "#c061cb"
red     = "#f66151"
white   = "#ffffff"
yellow  = "#e9ad0c"

[colors.normal]
black   = "#171421"
blue    = "#12488b"
cyan    = "#2aa1b3"
green   = "#26a269"
magenta = "#a347ba"
red     = "#c01c28"
white   = "#d0cfcc"
yellow  = "#a2734c"

[colors.primary]
background        = "#141414"
bright_foreground = "#ffffff"
dim_foreground    = "#828482"
foreground        = "#ffffff"

[font]
size = 8
normal = { family = "Source Code Pro", style = "Regular" }

[keyboard]
bindings = [
	{ action = "SpawnNewInstance", mods = "Control|Shift", key = "N" },
]

[window]
opacity = 0.95
padding.x = 2
padding.y = 2

