#=================#
# hyprland config #
#=================#


#------------------------------------------------------------#
# keywords - https://wiki.hyprland.org/Configuring/Keywords/ #
#------------------------------------------------------------#

$configPath = ~/.config/hypr/config

source = $configPath/binds.conf
source = $configPath/env.conf
source = $configPath/monitors.conf
source = $configPath/windows.conf
source = $configPath/workspaces.conf

exec-once = $configPath/startup.sh
exec      = $configPath/reload.sh


#--------------------------------------------------------------#
# variables - https://wiki.hyprland.org/Configuring/Variables/ #
#--------------------------------------------------------------#

general { # https://wiki.hyprland.org/Configuring/Variables/#general
	gaps_in = 2
	gaps_out = 4
	border_size = 2
	col.active_border = rgba(33ccffee) rgba(7766ccee) 45deg
	col.inactive_border = rgba(595959aa)

	layout = dwindle

	allow_tearing = false # visit https://wiki.hyprland.org/Configuring/Tearing/ before turning this on
}

input { # https://wiki.hyprland.org/Configuring/Variables/#input
	kb_layout = us
	kb_variant =
	kb_model =
	kb_options =
	kb_rules =

	follow_mouse = true

	sensitivity = -0.4 # float: [-1.0,1.0]
	accel_profile = flat

	#scroll_method = on_button_down
	#scroll_button = 274
	#scroll_button_lock = true
}

decoration { # https://wiki.hyprland.org/Configuring/Variables/#decoration
	rounding = 4
	
	blur {
		enabled = true
		size = 3
		passes = 1
		popups = true
	}

	drop_shadow = yes
	shadow_range = 4
	shadow_render_power = 3
	col.shadow = rgba(1a1a1aee)
}

animations { # https://wiki.hyprland.org/Configuring/Animations/
	enabled = yes

	bezier = myBezier, 0.05, 0.9, 0.1, 1.05

	animation = windows, 1, 7, myBezier
	animation = windowsOut, 1, 7, default, popin 80%
	animation = border, 1, 10, default
	animation = borderangle, 1, 8, default
	animation = fade, 1, 7, default
	animation = workspaces, 1, 6, default
}

dwindle { # https://wiki.hyprland.org/Configuring/Dwindle-Layout/
	pseudotile = yes
	preserve_split = yes
}

master { # https://wiki.hyprland.org/Configuring/Master-Layout/
	new_is_master = true
}

gestures { # https://wiki.hyprland.org/Configuring/Variables/
	workspace_swipe = off
}

misc {
	force_default_wallpaper = 0
}
