#====================================================================#
# window rules - https://wiki.hyprland.org/Configuring/Window-Rules/ #
#====================================================================#

windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = suppressevent,          class:^(steam)$

windowrulev2 = workspace 1,  class:^(discord)$
windowrulev2 = workspace 9,  class:^(steam)$
windowrulev2 = workspace 9,  class:^(Steam)$
windowrulev2 = workspace 9,  class:^(steamwebhelper)$
windowrulev2 = workspace 10, class:^(steam_app_.*)$
#windowrulev2 = worksapce 10, initialTitle:^(Godot)$

#windowrulev2 = float,                    title:^(flameshot)$
#windowrulev2 = move 0 0,                 title:^(flameshot)$
#windowrulev2 = suppressevent fullscreen, title:^(flameshot)$

windowrulev2 = float, title:^(File Operation Progress)$
windowrulev2 = float, title:^(Open Folder)$
windowrulev2 = float, title:^(Library)$
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(org\.gnome\.Calculator)$
windowrulev2 = float, class:^(nm-connection-editor)$


#---------------------#
# floating/tiling mix #
#---------------------#

#windowrulev2 = float, class:^(steam)$
#windowrulev2 = tile,  class:^(steam)$, title:^(Steam)$

windowrulev2 = float, class:^(thunderbird)$
windowrulev2 = tile,  class:^(thunderbird)$, title:^(Mozilla Thunderbird)$
